


















.build/nano328-bb502ab1/arduino/wiring_digital.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
include .build/nano328-bb502ab1/arduino/wiring_digital.d

.build/nano328-bb502ab1/arduino/wiring_analog.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
include .build/nano328-bb502ab1/arduino/wiring_analog.d

.build/nano328-bb502ab1/arduino/wiring_pulse.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/nano328-bb502ab1/arduino/wiring_pulse.d

.build/nano328-bb502ab1/arduino/wiring.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
include .build/nano328-bb502ab1/arduino/wiring.d

.build/nano328-bb502ab1/arduino/wiring_shift.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
include .build/nano328-bb502ab1/arduino/wiring_shift.d

.build/nano328-bb502ab1/arduino/WInterrupts.o : /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
include .build/nano328-bb502ab1/arduino/WInterrupts.d

.build/nano328-bb502ab1/arduino/avr-libc/realloc.o : /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/realloc.c
	@echo [93marduino/avr-libc/realloc.c[0m
	@mkdir -p .build/nano328-bb502ab1/arduino/avr-libc
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/realloc.c
include .build/nano328-bb502ab1/arduino/avr-libc/realloc.d

.build/nano328-bb502ab1/arduino/avr-libc/malloc.o : /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/malloc.c
	@echo [93marduino/avr-libc/malloc.c[0m
	@mkdir -p .build/nano328-bb502ab1/arduino/avr-libc
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/malloc.c
include .build/nano328-bb502ab1/arduino/avr-libc/malloc.d






.build/nano328-bb502ab1/arduino/new.o : /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
include .build/nano328-bb502ab1/arduino/new.d

.build/nano328-bb502ab1/arduino/main.o : /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
include .build/nano328-bb502ab1/arduino/main.d

.build/nano328-bb502ab1/arduino/USBCore.o : /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
include .build/nano328-bb502ab1/arduino/USBCore.d

.build/nano328-bb502ab1/arduino/HardwareSerial.o : /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/nano328-bb502ab1/arduino/HardwareSerial.d

.build/nano328-bb502ab1/arduino/CDC.o : /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
include .build/nano328-bb502ab1/arduino/CDC.d

.build/nano328-bb502ab1/arduino/Stream.o : /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
include .build/nano328-bb502ab1/arduino/Stream.d

.build/nano328-bb502ab1/arduino/WMath.o : /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
include .build/nano328-bb502ab1/arduino/WMath.d

.build/nano328-bb502ab1/arduino/Tone.o : /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
include .build/nano328-bb502ab1/arduino/Tone.d

.build/nano328-bb502ab1/arduino/Print.o : /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
include .build/nano328-bb502ab1/arduino/Print.d

.build/nano328-bb502ab1/arduino/WString.o : /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
include .build/nano328-bb502ab1/arduino/WString.d

.build/nano328-bb502ab1/arduino/HID.o : /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
include .build/nano328-bb502ab1/arduino/HID.d

.build/nano328-bb502ab1/arduino/IPAddress.o : /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/nano328-bb502ab1/arduino/IPAddress.d



.build/nano328-bb502ab1/arduino/libarduino.a : .build/nano328-bb502ab1/arduino/wiring_digital.o .build/nano328-bb502ab1/arduino/wiring_analog.o .build/nano328-bb502ab1/arduino/wiring_pulse.o .build/nano328-bb502ab1/arduino/wiring.o .build/nano328-bb502ab1/arduino/wiring_shift.o .build/nano328-bb502ab1/arduino/WInterrupts.o .build/nano328-bb502ab1/arduino/avr-libc/realloc.o .build/nano328-bb502ab1/arduino/avr-libc/malloc.o .build/nano328-bb502ab1/arduino/new.o .build/nano328-bb502ab1/arduino/main.o .build/nano328-bb502ab1/arduino/USBCore.o .build/nano328-bb502ab1/arduino/HardwareSerial.o .build/nano328-bb502ab1/arduino/CDC.o .build/nano328-bb502ab1/arduino/Stream.o .build/nano328-bb502ab1/arduino/WMath.o .build/nano328-bb502ab1/arduino/Tone.o .build/nano328-bb502ab1/arduino/Print.o .build/nano328-bb502ab1/arduino/WString.o .build/nano328-bb502ab1/arduino/HID.o .build/nano328-bb502ab1/arduino/IPAddress.o
	@echo [92mLinking libarduino.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^












.build/nano328-bb502ab1/TVOut/TVout.o : lib/TVOut/TVout.cpp
	@echo [93mTVOut/TVout.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/TVOut
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c lib/TVOut/TVout.cpp
include .build/nano328-bb502ab1/TVOut/TVout.d

.build/nano328-bb502ab1/TVOut/video_gen.o : lib/TVOut/video_gen.cpp
	@echo [93mTVOut/video_gen.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/TVOut
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c lib/TVOut/video_gen.cpp
include .build/nano328-bb502ab1/TVOut/video_gen.d

.build/nano328-bb502ab1/TVOut/TVoutPrint.o : lib/TVOut/TVoutPrint.cpp
	@echo [93mTVOut/TVoutPrint.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/TVOut
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c lib/TVOut/TVoutPrint.cpp
include .build/nano328-bb502ab1/TVOut/TVoutPrint.d

.build/nano328-bb502ab1/TVOut/TVoutfonts/font8x8.o : lib/TVOut/TVoutfonts/font8x8.cpp
	@echo [93mTVOut/TVoutfonts/font8x8.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/TVOut/TVoutfonts
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c lib/TVOut/TVoutfonts/font8x8.cpp
include .build/nano328-bb502ab1/TVOut/TVoutfonts/font8x8.d

.build/nano328-bb502ab1/TVOut/TVoutfonts/font4x6.o : lib/TVOut/TVoutfonts/font4x6.cpp
	@echo [93mTVOut/TVoutfonts/font4x6.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/TVOut/TVoutfonts
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c lib/TVOut/TVoutfonts/font4x6.cpp
include .build/nano328-bb502ab1/TVOut/TVoutfonts/font4x6.d

.build/nano328-bb502ab1/TVOut/TVoutfonts/font8x8ext.o : lib/TVOut/TVoutfonts/font8x8ext.cpp
	@echo [93mTVOut/TVoutfonts/font8x8ext.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/TVOut/TVoutfonts
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c lib/TVOut/TVoutfonts/font8x8ext.cpp
include .build/nano328-bb502ab1/TVOut/TVoutfonts/font8x8ext.d

.build/nano328-bb502ab1/TVOut/TVoutfonts/font6x8.o : lib/TVOut/TVoutfonts/font6x8.cpp
	@echo [93mTVOut/TVoutfonts/font6x8.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/TVOut/TVoutfonts
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions  -o $@ -c lib/TVOut/TVoutfonts/font6x8.cpp
include .build/nano328-bb502ab1/TVOut/TVoutfonts/font6x8.d



.build/nano328-bb502ab1/TVOut/libTVOut.a : .build/nano328-bb502ab1/TVOut/TVout.o .build/nano328-bb502ab1/TVOut/video_gen.o .build/nano328-bb502ab1/TVOut/TVoutPrint.o .build/nano328-bb502ab1/TVOut/TVoutfonts/font8x8.o .build/nano328-bb502ab1/TVOut/TVoutfonts/font4x6.o .build/nano328-bb502ab1/TVOut/TVoutfonts/font8x8ext.o .build/nano328-bb502ab1/TVOut/TVoutfonts/font6x8.o
	@echo [92mLinking libTVOut.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build/nano328-bb502ab1/src/sketch.o : .build/nano328-bb502ab1/src/sketch.cpp
	@echo [93msrc/sketch.cpp[0m
	@mkdir -p .build/nano328-bb502ab1/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -Ilib/TVOut -Ilib/TVOut/spec -Ilib/TVOut/TVoutfonts -fno-exceptions -iquote src  -o $@ -c .build/nano328-bb502ab1/src/sketch.cpp
include .build/nano328-bb502ab1/src/sketch.d







.build/nano328-bb502ab1/firmware.elf : .build/nano328-bb502ab1/src/sketch.o .build/nano328-bb502ab1/arduino/libarduino.a .build/nano328-bb502ab1/TVOut/libTVOut.a
	@echo [92mLinking firmware.elf[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/nano328-bb502ab1/firmware.hex : .build/nano328-bb502ab1/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/nano328-bb502ab1/src/dependencies.d .build/nano328-bb502ab1/arduino/dependencies.d .build/nano328-bb502ab1/TVOut/dependencies.d

all : .build/nano328-bb502ab1/firmware.hex
	@true

